import './globals.css';

import { Raleway } from 'next/font/google';
import React, { ReactNode } from 'react';

import Providers from '@/app/providers';
import ThemeSwitcher from '@/app/ThemeSwitcher';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} ctp-latte bg-ctp-base text-ctp-text accent-ctp-mauve scrollbar-thin scrollbar-track-ctp-base scrollbar-thumb-ctp-mauve scrollbar-thumb-rounded-lg dark:ctp-mocha`}
      >
        <Providers>
          <ThemeSwitcher />
          {children}
        </Providers>
      </body>
    </html>
  );
}
